### ISSUE TITLE
解决翻页卡顿建议

### ISSUE THREAD

**Issue by trustyboy** [leetomlee123/book#9]
这种方式的翻页TextPainter有性能问题，你给TextSpan指定下fontFamily会流畅非常多。

**Comment by leetomlee123** [comment]
至少目前短文本卡顿感知不明显   长的就很明显了

该是要等待flutter 修复

OK 这周试试

**Comment by trustyboy** [comment]
> 至少目前短文本卡顿感知不明显 长的就很明显了
> 
> 该是要等待flutter 修复
> 
> OK 这周试试

这个翻页应该是来自高仿书旗的那个项目吧，我之前也尝试解决过。
后面参考了这个：
https://github.com/flutter/flutter/issues/31774

**Comment by leetomlee123** [comment]
> > 至少目前短文本卡顿感知不明显 长的就很明显了
> > 该是要等待flutter 修复
> > OK 这周试试
> 
> 这个翻页应该是来自高仿书旗的那个项目吧，我之前也尝试解决过。
> 后面参考了这个：
> [flutter/flutter#31774](https://github.com/flutter/flutter/issues/31774)

的确  还是要等isolate中跑layout才是解决之道

**Comment by leetomlee123** [comment]
使用的是系统默认字体fontFamilyName 是啥呢

**Comment by trustyboy** [comment]
> 使用的是系统默认字体fontFamilyName 是啥呢

我是直接自带了一个字体

**Comment by leetomlee123** [comment]
> > 使用的是系统默认字体fontFamilyName 是啥呢
> 
> 我是直接自带了一个字体


> > 使用的是系统默认字体fontFamilyName 是啥呢
> 
> 我是直接自带了一个字体

我直接用roboto 也没引入字体  也可用

**Comment by trustyboy** [comment]
> > > 使用的是系统默认字体fontFamilyName 是啥呢
> > 
> > 
> > 我是直接自带了一个字体
> 
> > > 使用的是系统默认字体fontFamilyName 是啥呢
> > 
> > 
> > 我是直接自带了一个字体
> 
> 我直接用roboto 也没引入字体 也可用

嗯，应该都是可行的
